id: P003300
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS19069
  title: སྐྱེ་ལྡན་རྫས་འགྱུར་རིག་པ། སྟོད་ཆ།
  author: ''
  volumes:
    633fefde1b2e40508ea4102e8cf18f3e:
      image_group_id: I8LS19071
      title: ''
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
